site_name: æternity Documentation Hub
nav:
    - Introduction: 'index.md'
    - Quick Glossary: 'quick_glossary.md'
    - Node:
        - Introduction: 'aeternity/README.md'
        - Get Started:
            - Build in Windows: 'aeternity/docs/build-windows.md'
            - Build in Ubuntu: 'aeternity/docs/build.md'
            - Configuration: 'aeternity/docs/configuration.md'
            - CUDA Miner: 'aeternity/docs/cuda-miner.md'
            - Docker: 'aeternity/docs/docker.md'
            - Installation in Windows: 'aeternity/docs/installation-windows.md'
            - Installation in Ubuntu: 'aeternity/docs/installation.md'
            - Operation: 'aeternity/docs/operation.md'
    - Protocol:
        - Oracles:
            - Life Cycle: 'protocol/oracles/oracle_life_cycle.md'
            - State Tree: 'protocol/oracles/oracle_state_tree.md'
            - Transactions: 'protocol/oracles/oracle_transactions.md'
        - AENS Naming System: 'protocol/AENS.md'
        - Smart Contracts:
            - Contract Life Cycle Examples: 'protocol/contracts/contract_life_cycle.md'
            - Virtual Machines:
                - Æternity VM: 'protocol/contracts/contract_vms.md'
                - Æternity Ethereum VM: 'protocol/contracts/aevm.md'
            - Sophia Smart Contract Language: 'protocol/contracts/sophia.md'
            - Contract State Tree: 'protocol/contracts/contract_state_tree.md'
            - Contract Transactions: 'protocol/contracts/contract_transactions.md'
        - State Channels: 'protocol/channels/README.md'
        - Generalized Accounts: 'protocol/generalized_accounts/generalized_accounts.md'
        - Serialization Formats: 'protocol/serializations.md'
        - Stratum: 'protocol/STRATUM.md'
        - Sync: 'protocol/SYNC.md'
    - Aetmodel:
        - Threat Model: 'aetmodel/ThreatModel.md'
    - AEXs:
        - AEX1: 'AEXs/AEXS/aex-1.md'
        - AEX2: 'AEXs/AEXS/aex-2.md'
        - AEX3: 'AEXs/AEXS/aex-3.md'
        - AEX4: 'AEXs/AEXS/aex-4.md'
        - AEX5: 'AEXs/AEXS/aex-5.md'
        - AEX7: 'AEXs/AEXS/aex-7.md'
        - AEX9: 'AEXs/AEXS/aex-9.md'
        - AEX10: 'AEXs/AEXS/aex-10.md'
        - AEX-Draft: 'AEXs/AEXS/aex-draft_data_serialization.md'
    - Node Usage API:
        - Latest Stable Release:
            - Autogenerated æternity Node API Documentation: 'protocol/api-docs/README.md'
        - Encoding Scheme: 'protocol/node/api/api_encoding.md'
        - Account Managment: 'protocol/node/api/account_api_usage.md'
        - Spending Tokens: 'protocol/node/api/spend_api_usage.md'
        - Oracle: 'protocol/node/api/oracle_api_usage.md'
        - Naming System: 'protocol/node/api/naming_system_api_usage.md'
        - Contract: 'protocol/node/api/contract_api_usage.md'
        - Channels: 'protocol/node/api/channels_api_usage.md'
        - Mining: 'protocol/node/api/mining_api_usage.md'
    - Developer Tools:
        - æternity Framework:
            - AEproject: 'developer-tools/æternity-frameworks/aepp-aeproject-js/README.md'
        - Software Development Kits:
            - Go: 'developer-tools/sdks/aepp-sdk-go/README.md'
            - JavaScript: 'developer-tools/sdks/aepp-sdk-js/README.md'
            - Python: 'developer-tools/sdks/aepp-sdk-python/README.md'
            - Elixir: 'developer-tools/sdks/aepp-sdk-elixir/README.md'
            - Java: 'developer-tools/sdks/aepp-sdk-java/README.md'
        - Middleware: 'developer-tools/aepp-middleware/README.md'
        - Token Faucet: 'developer-tools/aepp-faucet/README.md'
        - Frameworks:
            - æpp Components: 'developer-tools/frameworks/aepp-components/README.md'
        - Contract Editor: 'developer-tools/aepp-contracts/README.md'
        - AirGap:
            - AirGap Coin Library: 'developer-tools/airgap/airgap-coin-lib/docs/README.md'
            - AirGap Vault: 'developer-tools/airgap/airgap-vault/README.md'
            - AirGap Wallet: 'developer-tools/airgap/airgap-wallet/README.md'
    #     - CLI Tools:
    #         - JavaScript
    #         - Stratum:
    #            - Library
    #         - Websocket
    #    - Online Test Tools:
    #         - Smart Contract Editor
    #         - Blockchain Explorer
    #         - Faucet
    #            - Token Faucet
    #            - æpp Faucet
    - Sophia Compiler:
        - aesophia: 'aesophia/README.md'
    - Sophia Libraries:
        - DateTime: 'aepp-sophia-examples/libraries/DateTime/README.md'
        - List: 'aepp-sophia-examples/libraries/List/README.md'
        - Ownable: 'aepp-sophia-examples/libraries/Ownable/README.md'
        - FungibleToken: 'aepp-sophia-examples/libraries/FungibleToken/README.md'
        - NonFungibleToken: 'aepp-sophia-examples/libraries/NonFungibleToken/README.md'
        - MultisignatureWallet: 'aepp-sophia-examples/libraries/MultisignatureWallet/README.md'
extra_css: [site/assets/extra.css]
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

repo_name: 'aeternity/documentation-hub'
repo_url: 'https://github.com/aeternity/documentation-hub'
